apiVersion: v1
kind: Service
metadata:
    name: cloud-downloader-api-service
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
    externalTrafficPolicy: Local
    type: LoadBalancer
    selector:
        app: service
    ports:
      - protocol: TCP
        port: 80
        targetPort: 5000
