apiVersion: v1
kind: Pod
metadata:
    name: aws-cli
spec:
    serviceAccountName: cdkstackcdkstackclustereksuser3717f006
    containers:
        - name: aws-cli
          image: amazon/aws-cli:latest
          command:
              - sleep
              - "3600"
          imagePullPolicy: IfNotPresent
    restartPolicy: Always
